### ISSUE TITLE
[Consensus] Write-up rationale for VDFs in EC

### ISSUE THREAD

**Issue by sternhenri** [filecoin-project/consensus#25]
**What it is**
This could take a number of formats (GH comment below, doc, etc), but it simply seeks to rationalize in a single artefact why EC needs VDFs. This includes arguments about:
- PoS replication of PoW guarantees (specifically for SPC)
- Potential attacks that are mitigated by VDF

**Why it matters**
This is a question we keep discussing, having this para could help generally onboard or level people up/track our thinking.

**Comment by ZenGround0** [comment]
Hey I know this is closed which is fine by me as I don't think this is launch blocking.  But for more info on this topic see [this issue](https://github.com/filecoin-project/aq/issues/129) in the archived aq repo.

**Comment by sternhenri** [comment]
Thanks @ZenGround0 I closed it for the reason you point out and the fact I think we have adequately aligned as a research team on why we want VDFs. For quick summary (I will provide longer write up in a forthcoming paper):

VDFs allow us to:
- Get rid of clock synchrony assumption that most consensus algorithms make, by effectively enforcing clock synchrony through waiting.
- Prevent folks from simulating the chain in the past (useful for a series of attacks), aside from the entropy provided by multiple participants on the chain
- Likewise prevent ticket grinding in running leader election, ensuring that elections remain power based rather than compute based (as one might by grinding through tickets in parallel)
- Prevent miners from rushing the protocol, thereby hurting miners who have worst connections and impacting protocol fairness.
