### ISSUE TITLE
Subtle and maybe wrong dependence among sim randomness

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/consensus#46]
In the sim we use the same random value for [election proof](https://github.com/filecoin-project/consensus/blob/master/code/ec-sim-zs/main.go#L267) and the [block's new ticket](https://github.com/filecoin-project/consensus/blob/master/code/ec-sim-zs/main.go#L264).  This goes against the protocol's separation of the two values (at least when lbp > 1).  While using the same value might not matter it is possible the dependence between the two random values is causing weird and subtle effects in the simulation that might skew results in weird undetectable way.

It looks like randomness sampling is going to need to change to conform to the latest EC spec update anyway, so doing that ASAP and getting it right (i.e. mimicing the actual protocol and sampling 2 different values) is probably the best way to make sure things aren't weird.

**Comment by sternhenri** [comment]
fixed here: https://github.com/filecoin-project/consensus/commit/831edf9245240d0c0f610b1e845b86e7305c46b8
