### ISSUE TITLE
EC EPoSt Questions

### ISSUE THREAD

**Issue by sternhenri** [filecoin-project/consensus#77]
- Lookback has to be 1 given SDR PoSt, which is an issue in EC reduction to Praos. Increases forkiness since no lookback means every sybil is running a local lottery with Leader Election.
- EC Weighting function should be updated to be dependent on number of tickets on chain (rather than blocks), since in EPoSt powerful parties can submit only a single block (with multiple tickets), those blocks have more "stake" (storage) behind them than ones with fewer tickets, so should be weighted accordingly.

**Comment by ZenGround0** [comment]
I wonder if you can factor in the Epost "slowness"/"expensive" factor into the framework reducing to praos.  When I've brought up the lookback = 1 in the past the only satisfying answer I've gotten back is that grinding will be more[slow/expensive] than in PoS because you need to traverse your sectors for every block.

**Comment by sternhenri** [comment]
It's an interesting point @ZenGround0 but we move into a model dealing with miner economic power (ie cost of grinding) which weakens our security model a lot and makes the analysis way hairier. Imo we should seek to prove it secure without it if we can, I worry this isn't what will save us if we can't.

**Comment by ZenGround0** [comment]
> I worry this isn't what will save us if we can't

I think it's a reasonable thing to be worried about but also hard to do without.  It seems to come down to the traditional [Nothing at Stake](https://github.com/ethereum/wiki/wiki/Proof-of-Stake-FAQ#what-is-the-nothing-at-stake-problem-and-how-can-it-be-fixed) issue which is always going to be a problem in the stronger model that doesn't account grinding cost.

**Comment by sternhenri** [comment]
closer per EPost not a thing
